dist: bionic
language: shell
services:
  - docker
script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull alpine:latest
  - docker pull postgres:13
  - docker pull golang:1.16-alpine
  - docker pull golang:1.13-alpine3.10
  - echo "Done!!"